# INSTABOOST Configuration

# Random seed settings
random_seed: 42  # Set to null for random behavior or an integer for deterministic behavior


# Model settings
model:
  name: "mistralai/Mistral-7B-Instruct-v0.1"
  device: "auto"  # "auto", "cuda", "mps", or "cpu"

# INSTABOOST parameters
instaboost:
  multiplier: 10.0
  boost_middle_layers_only: true
  num_middle_layers: 5
  start_layer: 8
  head_boost_percentage: 0.2

# Generation parameters
generation:
  temperature: 0.0
  max_new_tokens: 150
  top_p: 1.0

# Test parameters
testing:
  num_runs: 1
